name: Bot
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create GitHub Release
    if: github.repository == 'ashutoshgngwr/noice'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags -f
      - id: tag_info
        run: |
          export TAG_NAME="${GITHUB_REF/'refs/tags/'/''}"
          export TAG_BODY="$(git tag  --list --format='%(contents:body)' $TAG_NAME)"
          export TAG_BODY="${TAG_BODY//'%'/'%25'}"
          export TAG_BODY="${TAG_BODY//$'\n'/'%0A'}"
          export TAG_BODY="${TAG_BODY//$'\r'/'%0D'}"
          echo "::set-output name=name::${TAG_NAME}"
          echo "::set-output name=body::${TAG_BODY}"
      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tag_info.outputs.name }}
          body: ${{ steps.tag_info.outputs.body }}

  generate-docs:
    name: Generate Docs
    if: github.repository == 'ashutoshgngwr/noice'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - run: ./scripts/generate-docs.sh
        env:
          CHANGELOG_PATH: docs/CHANGELOG.md
          CONTRIBUTORS_YAML_PATH: docs/_data/authors/code.yaml
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
